spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?useUnicode=yes&characterEncoding=UTF-8&useSSL=false #防止中文乱码
    username: root
    password: 123456
  jpa:
    show-sql: true  #调试时显示SQL
  redis:
    host: localhost
    port: 6379   #无密码

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.netflix.feign: debug
