eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?useUnicode=yes&characterEncoding=UTF-8&useSSL=false 
    username: root
    password: 123456
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
env:
  dev
