spring:
  application:
    name: itcast-microservice-order #指定服务名
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@11.101.50.124:1521:orcl
    username: scott
    password: tiger

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry:  true  #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
      
env:
  dev
