spring:
  application:
    name: product #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.2:3306/SpringCloud_Sell?useUnicode=yes&characterEncoding=UTF-8&useSSL=false 
    username: root
    password: 123456
  jpa:
    show-sql: true
  rabbitmq:
    host: 10.211.55.2
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry:  true  #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true   #docker 显示IP，而不是用的 053839b3d8ad:config:6001
      
env:
  dev
